### Spring properties
# Service registers under this name
spring:
  application:
    name: apigateway

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8763


    
zuul:
  routes:
    user:
     path: /zuuluser/**
     serviceId: UserService        
    note:
     path: /zuulnote/**
     serviceId: DiscoveryEurekaNoteService
    sensitive-Headers: userId
    

 

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:50000

ribbon: 
  ReadTimeout: 50000
  ConnectTimeout: 55000 


  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000